export const startups = [
  {
    name: 'Startup 1',
    description: 'Description 1',
    avatar_url: 'https://github.com/shadcn.png',
    avatar_fallback: 'S1',
    url: '/startups/1',
  },
  {
    name: 'Startup 2',
    description: 'Description 2',
    avatar_url: 'https://github.com/shadcn.png',
    avatar_fallback: 'S2',
    url: '/startups/2',
  },
  {
    name: 'Startup 3',
    description: 'Description 3',
    avatar_url: 'https://github.com/shadcn.png',
    avatar_fallback: 'S3',
    url: '/startups/3',
  },
  {
    name: 'Startup 4',
    description: 'Description 4',
    avatar_url: 'https://github.com/shadcn.png',
    avatar_fallback: 'S4',
    url: '/startups/4',
  },
  {
    name: 'Startup 5',
    description: 'Description 5',
    avatar_url: 'https://github.com/shadcn.png',
    avatar_fallback: 'S5',
    url: '/startups/5',
  },
  {
    name: 'Startup 6',
    description: 'Description 6',
    avatar_url: 'https://github.com/shadcn.png',
    avatar_fallback: 'S6',
    url: '/startups/6',
  },
  {
    name: 'Startup 7',
    description: 'Description 7',
    avatar_url: 'https://github.com/shadcn.png',
    avatar_fallback: 'S7',
    url: '/startups/7',
  },
  {
    name: 'Startup 8',
    description: 'Description 8',
    avatar_url: 'https://github.com/shadcn.png',
    avatar_fallback: 'S8',
    url: '/startups/8',
  },
  {
    name: 'Startup 1',
    description: 'Description 1',
    avatar_url: 'https://github.com/shadcn.png',
    avatar_fallback: 'S1',
    url: '/startups/1',
  },
  {
    name: 'Startup 2',
    description: 'Description 2',
    avatar_url: 'https://github.com/shadcn.png',
    avatar_fallback: 'S2',
    url: '/startups/2',
  },
  {
    name: 'Startup 3',
    description: 'Description 3',
    avatar_url: 'https://github.com/shadcn.png',
    avatar_fallback: 'S3',
    url: '/startups/3',
  },
  {
    name: 'Startup 4',
    description: 'Description 4',
    avatar_url: 'https://github.com/shadcn.png',
    avatar_fallback: 'S4',
    url: '/startups/4',
  },
  {
    name: 'Startup 5',
    description: 'Description 5',
    avatar_url: 'https://github.com/shadcn.png',
    avatar_fallback: 'S5',
    url: '/startups/5',
  },
  {
    name: 'Startup 6',
    description: 'Description 6',
    avatar_url: 'https://github.com/shadcn.png',
    avatar_fallback: 'S6',
    url: '/startups/6',
  },
  {
    name: 'Startup 7',
    description: 'Description 7',
    avatar_url: 'https://github.com/shadcn.png',
    avatar_fallback: 'S7',
    url: '/startups/7',
  },
  {
    name: 'Startup 8',
    description: 'Description 8',
    avatar_url: 'https://github.com/shadcn.png',
    avatar_fallback: 'S8',
    url: '/startups/8',
  },
];
